sudo: required
language: go
go:
  - 1.12.x
  - 1.13.x
  - master
go_import_path: github.com/abulo/clickhouse-go
services:
  - docker
install:
  - export GO111MODULE="on"
  - go mod vendor

before_install:
  - docker --version
  - docker-compose --version
  - docker-compose up -d
script:
  - ./go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
